- hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu
  tasks:
    - name: Updating OS
      apt: update_cache=yes

    - name: Installing packages
      apt: name={{item}} state=latest
      with_items:
        - python3
        - python3-pip
        - virtualenv
        - nginx
        - gunicorn

    - name: Starting on boot
      service: name={{item}} enabled=yes state=started
      with_items:
        - nginx
        - gunicorn

    - name: Cloning App github repo
      git: clone=yes repo=https://github.com/anyric/Yummy-Recipes-Api.git dest=/home/ubuntu/Yummy-Recipes-Api

    - name: Creating virtualenv
      command: virtualenv -p python3 /home/ubuntu/Yummy-Recipes-Api/venv

    - name: Installing requirements.txt
      command: pip3 install -r /home/ubuntu/Yummy-Recipes-Api/requirements.txt