- hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu
  tasks:
    - name: Updating OS
      apt: update_cache=yes

    - name: Installing packages
      apt: name={{item}} state=latest
      with_items:
        - python3
        - python3-pip
        - virtualenv
        - nginx
        - gunicorn

    - name: Starting on boot
      service: name={{item}} enabled=yes state=started
      with_items:
        - nginx
        - gunicorn

    - name: Cloning App github repo
      git: clone=yes repo=https://github.com/anyric/Yummy-Recipes-Api.git dest=/home/ubuntu/Yummy-Recipes-Api

    - name: Creating virtualenv
      command: virtualenv -p python3 /home/ubuntu/Yummy-Recipes-Api/venv

    - name: Installing requirements.txt
      command: pip3 install -r /home/ubuntu/Yummy-Recipes-Api/requirements.txt
    #tested upto here above and working
    
    - name: Removing old app.py
      command: rm -rf /home/ubuntu/Yummy-Recipes-Api/app.py

    - name: Configuring app IP address
      copy: src=app.py des=/home/ubuntu/Yummy-Recipes-Api/app.py
  
    - name: Removing nginx default.conf
      command: rm -rf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

    - name: Copying nginx configuration
      template: src=yummy.conf dest=/etc/nginx/sites-available/yummy.conf
    
    - name: Creating symb link
      command: ln -s /etc/nginx/sites-available/yummy /etc/nginx/sites-enabled/
    
    - name: Granting firewall access
      command: ufw allow 'Nginx Full'
    
    - name: Starting Nginx
      command: systemctl start nginx
    
    - name: Creating script for Systemd
      copy: src=yummy.sh des=/home/ubuntu/Yummy-Recipes-Api/yummy.sh
  
    - name: Exporting Database URL
      command: export DATABASE_URL="postgres://postgres:postgres1234@postgresdb.cztrtf3jyreo.us-east-2.rds.amazonaws.com:5432/yummy_api"
  
    - name: Creating Systemd service file
      copy: src=yummy.service /home/ubuntu/Devops/Yummy-Recipes-Api/yummy.service

    - name: Reloading service Daemon
      command: systemctl daemon-reload

    - name: Enabling yummy app
      command: systemctl enable yummy
    
    - name: Starting yummy app
      command: systemctl start yummy
    
    